services:
  db:
    image: postgres
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./pw.sql:/docker-entrypoint-initdb.d/pw.sql
    ports:
      - 5432:5432
    secrets:
      - db_password
volumes:
  db:

secrets:
  db_password:
    file: ~/.pw_butler/db/password
